pde_type: ss_navier_stokes
model: non-wt-no-inj
ntrain: 4000
ntest: 500
sub: 1  # sub-sampling rate
num_workers: 2
frame_number: [-1]

# Dataloader specific values
precomp_stats_file:
test_base_index: -1
normalize: False 

batch_size: 32
epochs: 500
modes: 12  # number of modes to keep after FFT
width: 32
depth_per_block: 1
add_mlp: True 
in_channels: 2
out_channels: 1
res: 255

# Learning Rate Info
lr_schedule: constant
lr: 1e-3
step_size: 50  # for the step lr learning schedule
gamma: 0.5  # used for Step lr learning Schedule

# Deq Solver Information
solver: anderson  # (another one to use: broyden)
eps: 0.001  # maximum absolute residual for solver
solver_steps: 16
pretrain_steps: 300
pretrain_iter_steps: 1
add_noise_to_inputs: False 

# Phantom Gradients
use_pg: False  #Whter to use phantom training for training DEQs
tau: 0.25  # damping factor in phantom gradients
pg_steps: 1  #number of phantom gradient steps

# Noise Related Information
randomize_noise: False  # If to use random levels of noise or fixed noise during training
noisy_data: False  # if true: load_data will load noisy data. 
uniform_noise: False
lower_bound: -0.0009765625  # 1./1024  # lower bound for uniform sampling;
upper_bound: 0.0009765625  # 1./1024  # upper bound for uniform sampling;
noise_level: 0  # maximum noise level in the observation: this is added during the Training time

# Info Regarding storing and loggings
# data_base_path: '/path/to/data'
# model_base_path: '/path/to/dir/to/store/models'
# data_base_path: '/project_data/datasets/apokle_exp/deq-pde/PDE_datasets/jax_cfd_ns/data_with_forcing'
data_base_path: '/scratch/apokle/full_kolmogorov_wavenum_1_mv_5'
model_base_path: '/project_data/datasets/apokle_exp/deq-pde/FNO_ckpts/full_kolmogorov_wavenum_1_mv_5'  # NOTE: ask ashwini to change this

model_save_folder_path: models_${pde_type}/${model}/add_noise_to_input_${add_noise_to_inputs}/noise_level_${noise_level}
ckpt: lr_${lr}_ep_${epochs}_ntrain_${ntrain}_${now:%Y-%m-%d_%H-%M-%S}  # prefix for the checkpoint name
dataset: None  # name for the dataset to be used.
test_dataset: None
logging_freq: 100

use_wandb: True
wandb_prefix: run
train: True

# Structured noise
structured_noise: False  # whether to add random structured noise during training
noise_magnitude: 1.0  # magnitude of the structured noise to be added during training
seed: 0  # seed for exp

deq_args:
  # DEQ related config parameters
  f_solver: anderson
  b_solver: anderson

  f_max_iter: 12
  b_max_iter: 12

  f_eps: 0.001
  b_eps: 0.001

  f_stop_mode: abs
  b_stop_mode: abs 

  eval_factor: 1.5
  eval_f_thres: 12

  norm_type: weight_norm # Other choices are spectral norm and none
  norm_no_scale: False 
  norm_clip: False 
  norm_clip_value: 1.0
  norm_target_norm: 1.0
  sn_n_power_iters: 1.0

  core: sliced
  ift: False 
  hook_ift: False 
  n_losses: 1
  indexing: []
  gamma: 0.8
  phantom_grad: [1]
  tau: 1.0
  sup_gap: -1
  sup_loc: []

  jac_loss_weight: 0.0
  jac_loss_freq: 0.0
  jac_incremental: 0

  sradius_mode: False 
